### ISSUE TITLE
Find a good dataset and research question

### ISSUE THREAD

**Issue by slappyslop** [slappyslop/dsci-100-002-033#1]
IF you find something interesting, add it as a comment to this issue

**Comment by lding219** [comment]
found some interesting ones:
https://www.kaggle.com/datasets/imyjoshua/average-time-spent-by-a-user-on-social-media
https://www.kaggle.com/datasets/smmmmmmmmmmmm/canada-real-estate
https://www.kaggle.com/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024

**Comment by thido1** [comment]
I found some cool datasets

https://www.kaggle.com/code/eduarp/sickle-cell-anemia
dataset for different diseases (in pdf) https://cdas.cancer.gov/datasets/nlst/#:~:text=The%20Lung%20Cancer%20dataset%20(~,available%20in%20the%20Participant%20dataset.
Unemployment rate (excel file): https://open.canada.ca/data/en/dataset/f212a64f-92f0-430c-a04f-06436b1239d2/resource/c074e8a4-5d53-4b6e-9f3c-ca8b0f89035c

**Comment by lding219** [comment]
https://www.kaggle.com/datasets/kanchana1990/apple-music-dataset-10000-tracks-uncovered?rvi=1

**Comment by slappyslop** [comment]
https://www.kaggle.com/datasets/jeremylarcher/canadian-house-prices-for-top-cities

**Comment by slappyslop** [comment]
https://www.kaggle.com/datasets/jeremylarcher/canadian-house-prices-for-top-cities

We've decided on this dataset
